name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Build
        run: mvn clean package

      - name: Configure JFrog
        run: |
          jf config add artifactory \
            --url=${{ secrets.JF_URL }} \
            --user=${{ secrets.JF_USER }} \
            --password=${{ secrets.JF_TOKEN }} \
            --interactive=false

      - name: Upload Artifact
        run: |
          jf rt u "target/*.jar" "maven-demo-local1/"
